version: '3'
services:
    adminer:
        image: adminer:latest
        restart: always
        ports:
          - 3037:8080
        environment:
          ADMINER_DEFAULT_SERVER: "db"
          ADMINER_DESIGN: "hydra"
        networks:
          - inscricoes

    db:
        image: mariadb:latest
        restart: always
        ports:
          - '${DB_PORT:-3306}:5432'
        environment:
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
          - 'inscricoes:/var/lib/mysql'
        networks:
          - inscricoes

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '${REDIS_PORT:-6379}:6379'
      command: 'redis-server --requirepass ${REDIS_PASSWORD}'
      volumes: 
        - 'cache:/data'

networks:
  inscricoes:
    driver: bridge

volumes:
  inscricoes:
    driver: local
  cache:
    driver: local
